### ISSUE TITLE
[Q&A] How do I use it?

### ISSUE THREAD

**Issue by bachig26** [Layendan/NineAnimator-Tauri#11]
Hi,

I just found this project and installed the latest beta build. It asks for a source URL (github source link) and I'm confused how to use it.

I can understand that it's not yet complete to the level of the NineAnimator, but I also want to ask if the providers are to be added as the API based and what providers can I expect?

**Comment by Layendan** [comment]
The source is just a placeholder for later when I add that functionality. At the moment I use `google.com` but any valid url that does not return an error code will work. (eg. youtube.com, netflix.tv...)

**Comment by bachig26** [comment]
> The source is just a placeholder for later when I add that functionality. At the moment I use `google.com` but any valid url that does not return an error code will work. (eg. youtube.com, netflix.tv...)

Okay got ya👍
Thanks.

**Comment by LiLCavee** [comment]
hey!
The option add anime source isn't sth i fully understand
could u help give me a detailed way of using it.
thanks
