### ISSUE TITLE
Sources aren't working

### ISSUE THREAD

**Issue by protonssss** [Layendan/NineAnimator-Tauri#30]
![Screenshot 2023-12-09 015917](https://github.com/Layendan/Layendanimator/assets/140023475/1f24a5a3-aa8f-4337-bc74-0912c5c2971b)
App Version: 0.1.47

**Comment by Layendan** [comment]
Yeah I'm currently trying to fix the api right now only videos work, but nothing else does. I'll switch it back temporarily so that everything but the videos work.

**Comment by Layendan** [comment]
Fixed as of 5 minutes ago. You can try using the app again and it should work.
