### ISSUE TITLE
it wont open when i double click on the exe 

### ISSUE THREAD

**Issue by BuiiBuii1** [Layendan/NineAnimator-Tauri#31]
i install it and tried running admin and everything but nothing works

**Comment by Layendan** [comment]
What windows version are you using? I'm not entirely sure, but I have a feeling that the app might crash if it's not running on windows 11. If I'm right I'll try and implement a change that should fix it.

**Comment by BuiiBuii1** [comment]
im running windows 10 right now

**Comment by Layendan** [comment]
Yeah I think it's an issue with how I only implemented a feature to run on windows 11. Imma try make a fix and I'll ping you when implemented.

**Comment by Layendan** [comment]
@darkassassin182 
Can you try double clicking the app again and navigating to `C:\Users\__yourname__\AppData\Roaming\com.layendan.dev\logs`. You can do this by using `Win` + `r`, typing in `%appdata%` in the run dialog box, then navigate to `com.layendan.dev\logs`. Once at the logs could you please send me the file or copy paste the file contents?

**Comment by BuiiBuii1** [comment]
here the file [Layendanimator.log](https://github.com/Layendan/Layendanimator/files/14057906/Layendanimator.log)

**Comment by Layendan** [comment]
@darkassassin182 pushed a new update, please tell me if it's fixed. Apparently there might be some performance issues when resizing the app, but otherwise it should work correctly.
If there are performance issues, just let me know if they're too bad, if so I'll just remove window vibrance for windows 10.

Edit: You might have to re-download the app from github since I don't think the auto-updater would work in your context.

**Comment by BuiiBuii1** [comment]
sadly i still getting the same issue with the new update 
i have uninstalled the old version and still having the issue

**Comment by Layendan** [comment]
Could you send me the logs again please? That and could you go to your settings app, choose `System`, then go to `About` and send me your windows version and OS build? (You don't need to send anything else)
eg:
```
Edition	Windows 11 Home
Version	23H2
Installed on	‎1/‎13/‎2024
OS build	22631.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0
```
@darkassassin182 
btw, thank you for helping me test this out!

**Comment by BuiiBuii1** [comment]
[Layendanimator.log](https://github.com/Layendan/Layendanimator/files/14059606/Layendanimator.log)
Edition	Windows 10 Home
Version	22H2
Installed on	‎12/‎7/‎2023
OS build	19045.3930
Experience	Windows Feature Experience Pack 1000.19053.1000.0
oh you welcome happy i can help out @Layendan

**Comment by Layendan** [comment]
Surely it will work this time right?
@darkassassin182

**Comment by BuiiBuii1** [comment]
AYY IT WORK NOW YOUR THE GOAT
