### ISSUE TITLE
Gogo Anime Extention Down

### ISSUE THREAD

**Issue by LazyDevUserX** [Layendan/NineAnimator-Tauri#32]
Gogo anime extention unable to operate

1. Go to search
2. Click on Gogo
3. See error

**Expected behavior**
Gogo Anime extention loading anime

**Desktop (please complete the following information):**

- OS: Windows 10

**Comment by Layendan** [comment]
Working on my end.

What are you searching and what version are you using?
You can find the version by scrolling to the bottom of the settings page.
If you're using the latest version, try searching again.
I'm running the API on a less powerful server, so the initial load time to load up the API will sometimes be longer than 15 seconds which is the timeout for requests.
<img width="1552" alt="image" src="https://github.com/Layendan/Layendanimator/assets/46062388/a9ca3558-bc39-4412-8589-d48250dcbdb6">
<img width="1552" alt="image" src="https://github.com/Layendan/Layendanimator/assets/46062388/3ca85f9d-c17c-483e-9921-9c27f8b5cafd">
