### ISSUE TITLE
More consistent App icon

### ISSUE THREAD

**Issue by immyneedscake** [Layendan/NineAnimator-Tauri#33]
Lads/Lassies this is a great project, but one minor thing is that this needs a more consistent app icon (square with rounded corners) like other mac apps. Thankyou!

<img width="1030" alt="image" src="https://github.com/Layendan/Layendanimator/assets/8300027/842c0105-388f-44cc-993e-eade6b85f492">

**Comment by Layendan** [comment]
I was lazy and used the same icon for Windows and MacOS. Will be fixed in next update.

**Comment by Layendan** [comment]
Fixed in new update
