### ISSUE TITLE
Show other seasons and versions of a certain anime on the page

### ISSUE THREAD

**Issue by immyneedscake** [Layendan/NineAnimator-Tauri#35]
For example, if i look at a certain anime on a source,
<img width="1214" alt="image" src="https://github.com/Layendan/Layendanimator/assets/8300027/10cf7d6c-048f-468c-8104-fe99843ec17a">
it's not easy to get to Season 1 or Season 2 or any of the other related media like the movie etc.
<img width="1470" alt="image" src="https://github.com/Layendan/Layendanimator/assets/8300027/b9f73909-bcfc-4f5a-85a8-56dee9ed5845">

**Comment by Layendan** [comment]
I use Anilist as a database for this type of information, and they do not provide other seasons, only related animes (previous/next direct season like the second image, spin-offs based on that specific season, etc...). A good example would be One Piece where almost every spin-off are listen in the related tab, while a bad example would be demon slayer, where you have to navigate a whole bunch to find the season you want.

I can't really fix this issue, but if you want to find something similar, I recommend using the search function.
