### ISSUE TITLE
500: Internal Error 

### ISSUE THREAD

**Issue by ChiYuP5R** [Layendan/NineAnimator-Tauri#38]
**Describe the bug**
Click on an anime, get error code 500: internal error

1. Open Layendanimator
2. Click any anime no matter the source

**Expected behavior**
load any anime

**Desktop (please complete the following information):**

- OS: Windows
- Version 1.413.25.0

log file states date and time alongside [tao::platform_impl::platform::event_loop::runner] RedrawEventsCleared emitted without explicit MainEventsCleared

**Comment by Layendan** [comment]
I'm trying to get this fixed without hosting a server but it's taking longer than expected.

I might host a server in the meantime to temporarily fix the app, then actually fix it later.

**Comment by Layendan** [comment]
Fixed in new update, I decided just to run the server myself since it'll be easier to work with in the long run
