### ISSUE TITLE
[Q&A] Add sources

### ISSUE THREAD

**Issue by MisterPur** [Layendan/NineAnimator-Tauri#39]
How do I add as source Aniwave. I see nothing that talks about that

**Comment by Layendan** [comment]
I technically haven't implemented that part yet. It is possible to add sources but the feature is not built enough to handle a full fledged scraper.

If you have experience with coding and/or have access to hosting a server then it would be possible. Otherwise, not yet.

**Comment by Shouri14** [comment]
Hey @Layendan, Can you please point to the place where settings file is located in mac ? (Trying to add new sources in code)
Thank you.

**Comment by Layendan** [comment]
> Hey @Layendan, Can you please point to the place where settings file is located in mac ? (Trying to add new sources in code) Thank you.

Currently user data is loaded in https://github.com/Layendan/Layendanimator/blob/master/src/lib/model/settings.ts with sources being implemented here https://github.com/Layendan/Layendanimator/blob/master/src/lib/model/source.ts you can use this as a base for creating a new source:
[KickAssAnime.json](https://github.com/user-attachments/files/17449456/KickAssAnime.json)
(You can get it by right clicking kickassanime on the left side and choosing export source)

These get ran basically as just eval, but missing a few APIs which makes scraping a bit harder (what I really wanted to fix before working on other stuff). So currently I just have a scraper API hosted online and am calling that API through normal fetches inside the app.
@Shouri14
