### ISSUE TITLE
Error: Network Error

### ISSUE THREAD

**Issue by Shouri14** [Layendan/NineAnimator-Tauri#43]
**Describe the bug**
App doesn't load anything. Says Network Error

**To Reproduce**

1. Launch the app

**Expected behavior**
Expect app to load from one of the sources

**Screenshots**
![image](https://github.com/user-attachments/assets/0962178c-cad1-44f8-a663-196682f96001)

**Desktop (please complete the following information):**

- OS: Windows
- Version 22H2

**Additional context**
The only thing I could think of was that my NordVPN might be blocking the connection. I added the app to bypass vpn (split tunneling) but it didn't help.
In network monitor I only see outgoing packets.

Log Content:
```
[2024-10-19][07:52:27][[31mERROR[0m][app] Failed to connect to Discord IPC client - main
[2024-10-19][07:52:52][[33mWARN[0m][tao::platform_impl::platform::event_loop::runner] NewEvents emitted without explicit RedrawEventsCleared
[2024-10-19][07:52:52][[33mWARN[0m][tao::platform_impl::platform::event_loop::runner] RedrawEventsCleared emitted without explicit MainEventsCleared
```

Really nice app, keep up the good work.
Hopefully this issue can be resolved.

**Comment by Shouri14** [comment]
Note - Tried bypassing windows firewall, didn't work

**Comment by Layendan** [comment]
Make sure that you're using the kickassanime source since that's the only one that's working. If you get the error on that source, you can reload the page and it should work (either top left in navigation or `ctrl+r`).


> Really nice app, keep up the good work.

Thanks! I haven't touched this code base in a while and there's a lot of issues (at least UI/UX wise), maybe I'll get around to fixing them.

**Comment by Shouri14** [comment]
> Make sure that you're using the kickassanime source since that's the only one that's working. If you get the error on that source, you can reload the page and it should work (either top left in navigation or `ctrl+r`).

I tried what you suggested. Didn't work.
Did the same with other sources for any luck, but nope.

Thought about adding a new source `https://hianime.to` but was getting below error,
![image](https://github.com/user-attachments/assets/52e1d2e4-3593-4576-a27f-d532f2138ff5)

**Comment by Shouri14** [comment]
Was able to resolve it.
In network monitor, the connections were showing up under `Microsoft Edge WebView2` instead of `Layendanimator`.
I had a rule blocking connections on `Microsoft Edge WebView2` hence the issue. 

FYI - 
Through GUI was having new issues adding new sources but was able to get it to work by directly updating `.settings.dat`
I added hianime.to (I personally like this website)

Out of all the other anime viewing app projects, I like your best. I'll keep an eye out in-case you decide to continue updating the app.

Cheers!

**Comment by Layendan** [comment]
Glad you were able to figure it out and thanks for the compliments!
